spring.datasource.url=jdbc:postgresql://postgresql:5432/ticketguru
spring.datasource.username=ticketguru
spring.datasource.password=okTiimi
spring.datasource.driver-class-name=org.postgresql.Driver

# Disable Hibernate automatic schema creation/update
spring.jpa.hibernate.ddl-auto=none

# Show SQL in console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Initialize schema and data from your SQL scripts
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:data.sql
spring.sql.init.data-locations=classpath:data.sql